### ISSUE TITLE
I think show remove the useless code in blazor eshop.

### ISSUE THREAD

**Issue by cysnet** [dotnet-architecture/eShopOnBlazor#16]
The code **_ApplicationModule_**   should be removed in blazor. It make someone confused because it's useless.

![image](https://user-images.githubusercontent.com/35944271/184781908-c76e78c3-3383-4bbb-9dda-581afb6ed963.png)

**Comment by ardalis** [comment]
Good catch - it seems that's only being used in the web forms project.
