### ISSUE TITLE
Getting path error for web forms project.

### ISSUE THREAD

**Issue by akoranteng** [dotnet-architecture/eShopOnBlazor#20]
Can you reopen the case for the path not   found error reported on Dec, 15 2020. I am still getting the error when I run the webforms project.

![2023-02-26_09-06-13_Path_Error](https://user-images.githubusercontent.com/13998322/221416129-911e63ae-0682-4f5a-be4f-bb762e639bf8.jpg)

**Comment by ardalis** [comment]
Just did a fresh clone to a new Win11 machine with VS2022 installed and it runs first try. What is your system setup?
