### ISSUE TITLE
Image is squished on details page

### ISSUE THREAD

**Issue by jamesmontemagno** [dotnet-architecture/eShopOnBlazor#26]
![image](https://github.com/dotnet-architecture/eShopOnBlazor/assets/1676321/dbfa06ba-1edc-4f41-ba67-65bb10b1258f)

**Comment by SrushtiPasari94** [comment]
@jamesmontemagno Converted the links to button. Let me know if any other changes required in this Details Page

![image](https://github.com/dotnet-architecture/eShopOnBlazor/assets/136682990/cedb60c0-22b5-4e44-9a3d-40a0f7b9cad4)

**Comment by jamesmontemagno** [comment]
any way for it to keep it's aspect ratio?
