### ISSUE TITLE
Edit page details are shifted to right, but should be centered

### ISSUE THREAD

**Issue by jamesmontemagno** [dotnet-architecture/eShopOnBlazor#27]
![image](https://github.com/dotnet-architecture/eShopOnBlazor/assets/1676321/2e53d129-e131-4c49-b01d-54943906a8b9)

**Comment by SrushtiPasari94** [comment]
Cantered the Edit page details.

![image](https://github.com/dotnet-architecture/eShopOnBlazor/assets/136682990/bfe8f005-be2b-4dbf-bd36-7e45444e256e)
