### ISSUE TITLE
Details page should have buttons

### ISSUE THREAD

**Issue by jamesmontemagno** [dotnet-architecture/eShopOnBlazor#28]
![image](https://github.com/dotnet-architecture/eShopOnBlazor/assets/1676321/49e78718-4565-410c-92df-4372407fd1d1)

**Comment by SrushtiPasari94** [comment]
@jamesmontemagno Converted the links to button. Let me know if any other changes required in this Details Page

![image](https://github.com/dotnet-architecture/eShopOnBlazor/assets/136682990/cedb60c0-22b5-4e44-9a3d-40a0f7b9cad4)

**Comment by jamesmontemagno** [comment]
Looks good
