### ISSUE TITLE
update to net core 3.1

### ISSUE THREAD

**Issue by ghd258** [dotnet-architecture/eShopOnBlazor#6]
update to net core 3.1

**Comment by justSteve** [comment]
Wondering what you'd expect of required changes. I've updated the project file to target 3.1:

```
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
...
  </PropertyGroup>
```

The project builds and runs seemingly just the same as before.

**Comment by ShadyNagy** [comment]
@danroth27 @twsouthwick 
I think this issue need to be closed.

**Comment by twsouthwick** [comment]
Looks like it's targeting 5.0 now. It should probably be updated to 6 soon

**Comment by ardalis** [comment]
That is the plan...
